In [2]:
import pandas as pd 
import altair as alt
import sys
sys.path.append('..')

In [3]:
data = pd.read_excel('../data/raw/final_data.xlsx', sheet_name='Student_Observations')
kc = pd.read_excel('../data/raw/final_data.xlsx', sheet_name='KC_Nodes')
mkc_data = pd.read_csv('../data/processed/mkc_data.csv')

`mkc_data` contains weights and pyBKT predictions for the MKCs.

pyBKT : each row gives the estimates for each KC for each student.

- `correct_predictions` : predicted probability that student answers that specific attempt correctly
- `state_predictions` : predicted probability that the student has mastered the skill at that point in time (P(Learned))

In [4]:
mkc_data.head()

,user_id,skill_name,correct,order_id,correct_predictions,state_predictions,modeling_kc_label,unit,topic_group,description,...,unit_description,weight,tier,estimated_exam_share_pct,unit_exam_weighting,direct_dependents,downstream_dependents,weighted_direct_edge_count,weight_rationale,2026_27_revision_note
0,S001,MKC.U3.05.blocking_matching_blinding_confounding,1,0,0.439994,0.172071,"Blocking, matched pairs, blinding, and confoun...",Unit 3,Experimental design,"Recognize blocked/matched-pairs designs, place...",...,Collecting Data,57,Tier 3: medium-high,2.63,12%–15%,1,1,3,high AP unit weighting,NaN
1,S001,MKC.U8.02.chi_square_two_way_structure,0,1,0.397735,0.484439,"Two-way chi-square structure, hypotheses, and ...",Unit 8,Chi-square inference,"Select homogeneity or independence procedures,...",...,Inference for Categorical Data: Chi-Square,35,Tier 4: medium,1.35,2%–5%,1,1,3,low AP unit weighting,NaN
2,S001,MKC.U4.04.binomial_model,0,2,0.443429,0.413403,Binomial model,Unit 4,Binomial distributions,"Check binomial conditions, use binomial formul...",...,"Probability, Random Variables, and Probability...",74,Tier 2: high,2.66,10%–20%,2,2,2,high AP unit weighting; aligns with high-weigh...,NaN
3,S001,MKC.U6.02.one_prop_hypothesis_tests,0,3,0.393887,0.300741,One-proportion hypothesis tests,Unit 6,Inference for proportions,"Select, set up, perform, and conclude one-prop...",...,Inference for Categorical Data: Proportions,96,Tier 1: critical,3.69,12%–15%,7,13,14,directly supports 7 MKCs; high AP unit weighting,NaN
4,S001,MKC.U9.01.slope_inference_foundations_ci,0,4,0.480459,0.701718,Regression slope inference foundations and con...,Unit 9,Inference for regression slope,"Select slope-inference procedures, identify sl...",...,Inference for Quantitative Data: Slopes,32,Tier 4: medium,1.21,2%–5%,1,2,3,low AP unit weighting,2026-27 AP revision removes Unit 9 slope infer...

## Distribution of KC mastery

It could be useful for a teacher to see how the distribution of students on KCs.

In [5]:
mkc_data.sort_values(['skill_name','user_id'])

,user_id,skill_name,correct,order_id,correct_predictions,state_predictions,modeling_kc_label,unit,topic_group,description,...,unit_description,weight,tier,estimated_exam_share_pct,unit_exam_weighting,direct_dependents,downstream_dependents,weighted_direct_edge_count,weight_rationale,2026_27_revision_note
69,S001,MKC.U1.01.data_context_variables,0,69,0.572580,0.502561,Data context and variable classification,Unit 1,Data foundations,"Recognize investigative context, observational...",...,Exploring One-Variable Data,89,Tier 1: critical,2.42,15%–23%,4,41,4,foundation for 41 downstream MKCs; high AP uni...,NaN
102,S002,MKC.U1.01.data_context_variables,1,11,0.572580,0.502561,Data context and variable classification,Unit 1,Data foundations,"Recognize investigative context, observational...",...,Exploring One-Variable Data,89,Tier 1: critical,2.42,15%–23%,4,41,4,foundation for 41 downstream MKCs; high AP uni...,NaN
120,S002,MKC.U1.01.data_context_variables,1,29,0.597781,0.655759,Data context and variable classification,Unit 1,Data foundations,"Recognize investigative context, observational...",...,Exploring One-Variable Data,89,Tier 1: critical,2.42,15%–23%,4,41,4,foundation for 41 downstream MKCs; high AP uni...,NaN
226,S003,MKC.U1.01.data_context_variables,1,68,0.572580,0.502561,Data context and variable classification,Unit 1,Data foundations,"Recognize investigative context, observational...",...,Exploring One-Variable Data,89,Tier 1: critical,2.42,15%–23%,4,41,4,foundation for 41 downstream MKCs; high AP uni...,NaN
252,S004,MKC.U1.01.data_context_variables,0,19,0.572580,0.502561,Data context and variable classification,Unit 1,Data foundations,"Recognize investigative context, observational...",...,Exploring One-Variable Data,89,Tier 1: critical,2.42,15%–23%,4,41,4,foundation for 41 downstream MKCs; high AP uni...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,S019,MKC.U9.03.slope_hypothesis_tests,1,21,0.396837,0.259181,Regression slope hypothesis tests,Unit 9,Inference for regression slope,"Select, set hypotheses for, calculate, interpr...",...,Inference for Quantitative Data: Slopes,29,Tier 5: low / enrichment,1.12,2%–5%,1,2,1,low AP unit weighting,2026-27 AP revision removes Unit 9 slope infer...
1499,S020,MKC.U9.03.slope_hypothesis_tests,0,34,0.396837,0.259181,Regression slope hypothesis tests,Unit 9,Inference for regression slope,"Select, set hypotheses for, calculate, interpr...",...,Inference for Quantitative Data: Slopes,29,Tier 5: low / enrichment,1.12,2%–5%,1,2,1,low AP unit weighting,2026-27 AP revision removes Unit 9 slope infer...
1602,S021,MKC.U9.03.slope_hypothesis_tests,1,46,0.396837,0.259181,Regression slope hypothesis tests,Unit 9,Inference for regression slope,"Select, set hypotheses for, calculate, interpr...",...,Inference for Quantitative Data: Slopes,29,Tier 5: low / enrichment,1.12,2%–5%,1,2,1,low AP unit weighting,2026-27 AP revision removes Unit 9 slope infer...
1775,S023,MKC.U9.03.slope_hypothesis_tests,0,58,0.396837,0.259181,Regression slope hypothesis tests,Unit 9,Inference for regression slope,"Select, set hypotheses for, calculate, interpr...",...,Inference for Quantitative Data: Slopes,29,Tier 5: low / enrichment,1.12,2%–5%,1,2,1,low AP unit weighting,2026-27 AP revision removes Unit 9 slope infer...
1927,S025,MKC.U9.03.slope_hypothesis_tests,0,59,0.396837,0.259181,Regression slope hypothesis tests,Unit 9,Inference for regression slope,"Select, set hypotheses for, calculate, interpr...",...,Inference for Quantitative Data: Slopes,29,Tier 5: low / enrichment,1.12,2%–5%,1,2,1,low AP unit weighting,2026-27 AP revision removes Unit 9 slope infer...

In [6]:
threshold = 0.95

hist = alt.Chart(mkc_data).transform_calculate(
    zone=f"""
        datum.state_predictions >= {threshold} ? 'Mastered' :
        datum.state_predictions >= 0.4 ? 'Developing' : 'At risk'
    """
).mark_bar().encode(
    x=alt.X('state_predictions:Q', bin=alt.Bin(maxbins=30), title='Mastery Probability'),
    y=alt.Y('count()', title='Count'),
    color=alt.Color('zone:N', scale=alt.Scale(
        domain=['At risk', 'Developing', 'Mastered'],
        range=['#e57373', '#f0a500', '#4caf77']
    ), legend=alt.Legend(title='Zone'))
)

# Mastery threshold line
rule = alt.Chart(pd.DataFrame({'x': [threshold]})).mark_rule(
    strokeDash=[4, 4], color='gray', size=1.5
).encode(x='x:Q')

(hist + rule).properties(title='Mastery Probability Distribution')

alt.LayerChart(...)

## KC dfficulty ranking

If we want to rank the KC difficulty by showing the % of the class that is below a certain threshold

In [7]:
threshold = 0.6
kc_difficulty = (
    mkc_data
    .groupby('skill_name')['state_predictions']
    .apply(lambda x: (x < threshold).mean() * 100)
    .reset_index()
    .rename(columns={'state_predictions': 'pct_not_mastered'})
    .sort_values('pct_not_mastered', ascending=False)
)

In [8]:
kc_difficulty

                                           skill_name  pct_not_mastered
16                  MKC.U3.02.bias_and_generalization        100.000000
38                   MKC.U7.04.two_sample_t_intervals        100.000000
18       MKC.U3.04.random_assignment_causation_design        100.000000
17               MKC.U3.03.study_type_variables_units        100.000000
21        MKC.U4.02.conditional_compound_independence        100.000000
22          MKC.U4.03.random_variables_expected_value        100.000000
37                       MKC.U7.03.one_sample_t_tests        100.000000
13     MKC.U2.04.regression_prediction_interpretation        100.000000
36             MKC.U7.02.matched_pairs_mean_inference        100.000000
35             MKC.U7.01.t_intervals_mean_foundations        100.000000
10          MKC.U2.01.two_way_categorical_association        100.000000
8         MKC.U10.03.effect_size_practical_importance        100.000000
7                      MKC.U10.02.bootstrap_intervals        100.000000
40        MKC.U7.06.multiple_comparisons_family_error        100.000000
34                MKC.U6.05.two_prop_hypothesis_tests        100.000000
4           MKC.U1.05.standardization_transformations        100.000000
29         MKC.U5.05.diff_means_sampling_distribution        100.000000
2         MKC.U1.03.quantitative_displays_description        100.000000
19   MKC.U3.05.blocking_matching_blinding_confounding        100.000000
9                   MKC.U10.04.power_typeii_tradeoffs         98.076923
46                   MKC.U9.03.slope_hypothesis_tests         96.969697
14           MKC.U2.05.residuals_r2_model_diagnostics         95.744681
32                       MKC.U6.03.errors_alpha_power         95.121951
27   MKC.U5.03.diff_proportions_sampling_distribution         94.285714
31                MKC.U6.02.one_prop_hypothesis_tests         91.836735
42             MKC.U8.02.chi_square_two_way_structure         90.909091
11             MKC.U2.02.scatterplots_and_association         90.000000
41                           MKC.U8.01.chi_square_gof         89.830508
33            MKC.U6.04.two_prop_confidence_intervals         88.571429
39                       MKC.U7.05.two_sample_t_tests         84.444444
26  MKC.U5.02.sample_proportion_sampling_distribution         81.818182
15              MKC.U3.01.population_sampling_methods         75.342466
0                    MKC.U1.01.data_context_variables         73.684211
6           MKC.U10.01.bootstrap_process_distribution         73.529412
3               MKC.U1.04.summary_statistics_outliers         73.076923
23                           MKC.U4.04.binomial_model         72.368421
43  MKC.U8.03.chi_square_two_way_calculation_concl...         68.750000
25             MKC.U5.01.normal_simulation_estimators         64.788732
20       MKC.U4.01.probability_foundations_simulation         61.224490
28        MKC.U5.04.sample_mean_sampling_distribution         58.823529
30            MKC.U6.01.one_prop_confidence_intervals         31.746032
44           MKC.U9.01.slope_inference_foundations_ci         17.948718
12      MKC.U2.03.correlation_form_outliers_transform         15.000000
5          MKC.U1.06.normal_distribution_calculations          9.375000
24                          MKC.U4.05.geometric_model          0.000000
1               MKC.U1.02.categorical_tables_displays          0.000000
45  MKC.U9.02.regression_conditions_diagnostics_scope          0.000000

Top 10 KCs with lowest mastery :

In [9]:
threshold = 0.7
kc_difficulty = (
    mkc_data
    .groupby('modeling_kc_label')['state_predictions']
    .mean()
    .reset_index()
    .rename(columns={'state_predictions': 'avg_mastery'})
    .sort_values('avg_mastery')
)

In [10]:
alt.Chart(kc_difficulty[:10]).mark_bar().encode(
    x=alt.X('avg_mastery', title = 'Average mastery'),
    y=alt.Y('modeling_kc_label', sort='x', title = 'Skill name'),
    tooltip=alt.Tooltip(['avg_mastery'], title = 'Average mastery')
).properties(
    title = 'Top 10 KCs with lowest Mastery Probability',
)

alt.Chart(...)

In [11]:
alt.Chart(kc_difficulty[-10:]).mark_bar().encode(
    x=alt.X('avg_mastery', title = 'Average mastery'),
    y=alt.Y('modeling_kc_label', sort='x', title = 'Skill name'),
    tooltip=alt.Tooltip(['avg_mastery'], title = 'Average mastery')
).properties(
    title = 'Top 10 KCs with highest Mastery Probability',
)

alt.Chart(...)

In [12]:
mkc_rank = mkc_data.groupby(['modeling_kc_label','rank']).count().sort_values('rank').reset_index()[['modeling_kc_label','rank']]
mkc_rank[:3]

                               modeling_kc_label  rank
0         Probability foundations and simulation     1
1  Summary statistics, percentiles, and outliers     2
2                One-proportion hypothesis tests     3

Notes : maybe only keep the latest state_prediction in the case that there are multiple

## KC progress

In [13]:
mkc_data = mkc_data.sort_values(['user_id', 'skill_name', 'order_id'])
mkc_data['kc_attempt'] = (
    mkc_data
    .groupby(['user_id', 'skill_name'])
    .cumcount() + 1
)
# Then average across students for each KC at each attempt number
mastery_over_time = (
    mkc_data
    .groupby(['kc_attempt', 'skill_name'])['state_predictions']
    .mean()
    .reset_index()
    .rename(columns={'state_predictions': 'avg_mastery'})
)
kc_selection = alt.selection_point(fields=['skill_name'], bind='legend')

alt.Chart(mastery_over_time).mark_line(point=True).encode(
    x=alt.X('kc_attempt:Q', title='Attempt number (per KC)'),
    y=alt.Y('avg_mastery:Q', title='Average mastery', scale=alt.Scale(domain=[0, 1])),
    color=alt.Color('skill_name:N', legend=alt.Legend(title='KC')),
    opacity=alt.condition(kc_selection, alt.value(1), alt.value(0.1)),
    tooltip=[
        alt.Tooltip('skill_name:N', title='KC'),
        alt.Tooltip('kc_attempt:Q', title='Attempt'),
        alt.Tooltip('avg_mastery:Q', title='Avg mastery', format='.3f')
    ]
).add_params(kc_selection).properties(
    title='Mastery over time per KC',
    width=500, height=300
)

alt.Chart(...)

In [14]:
kc_selection = alt.selection_point(fields=['skill_name'], bind='legend')

alt.Chart(mastery_over_time[mastery_over_time['skill_name']=='MKC.U6.02.one_prop_hypothesis_tests']).mark_line(point=True).encode(
    x=alt.X('kc_attempt:Q', title='Attempt number (per KC)'),
    y=alt.Y('avg_mastery:Q', title='Average mastery', scale=alt.Scale(domain=[0, 1])),
    tooltip=[
        alt.Tooltip('skill_name:N', title='KC'),
        alt.Tooltip('kc_attempt:Q', title='Attempt'),
        alt.Tooltip('avg_mastery:Q', title='Avg mastery', format='.3f')
    ]
).properties(
    title='Mastery over time per KC',
    width=500, height=300
)

alt.Chart(...)

In [15]:
first_attempt = mkc_data.groupby(['user_id','skill_name'])['state_predictions'].first().mean()
last_attempt = mkc_data.groupby(['user_id','skill_name'])['state_predictions'].last().mean()

print(f"Avg mastery at first attempt: {first_attempt:.3f}")
print(f"Avg mastery at latest attempt: {last_attempt:.3f}")

Avg mastery at first attempt: 0.378
Avg mastery at latest attempt: 0.431

## Correlation between KCs

In [16]:
kc_matrix = mkc_data.pivot_table(
    index='user_id',
    columns='skill_name',
    values='state_predictions',
    aggfunc='last'  # take each student's most recent mastery estimate per KC
)
corr_matrix = kc_matrix.corr().reset_index().melt(
    id_vars='skill_name',
    var_name='skill_name_2',
    value_name='correlation'
)

In [17]:
alt.Chart(corr_matrix).mark_rect().encode(
    x=alt.X('skill_name:N', title=None, axis=alt.Axis(labelAngle=-45, labelLimit=200)),
    y=alt.Y('skill_name_2:N', title=None, axis=alt.Axis(labelLimit=200)),
    color=alt.Color('correlation:Q', scale=alt.Scale(
        domain=[-1, 0, 1],
        range=['#e57373', '#ffffff', '#4caf77']  # red = negative, white = none, green = positive
    )),
    tooltip=[
        alt.Tooltip('skill_name:N', title='KC 1'),
        alt.Tooltip('skill_name_2:N', title='KC 2'),
        alt.Tooltip('correlation:Q', title='Correlation', format='.2f')
    ]
).properties(
    title='KC correlation heatmap',
    width=600,
    height=600
)

alt.Chart(...)

## Unit KC tiles

In [40]:
import pandas as pd
import altair as alt
import numpy as np
 
# ── colour constants ────────────────────────────────────────────────────────
 
MASTERED_FILL       = "#60D394"
MASTERED_STROKE     = "#34714F"
 
PROGRESS_FILL       = "#FFD97D"
PROGRESS_STROKE     = "#FFBA81"
 
IMPROVEMENT_FILL    = "#FF9B85"
IMPROVEMENT_STROKE  = "#EE6055"
 
TEXT_COLOR          = "#5F5E5A"
LABEL_COLOR         = "#888780"
BG_COLOR            = "#F5F4F0"
 
# ── helpers ─────────────────────────────────────────────────────────────────
 
def classify(score, mastery_threshold=0.70, warning_threshold=0.30):
    if score >= mastery_threshold:
        return "Mastered"
    elif score <= warning_threshold:
        return "Needs Improvement"
    else:
        return "Progressing"
 
 
def status_color(status: str, key: str) -> str:
    mapping = {
        "Mastered":          {"fill": MASTERED_FILL,    "stroke": MASTERED_STROKE},
        "Progressing":       {"fill": PROGRESS_FILL,    "stroke": PROGRESS_STROKE},
        "Needs Improvement": {"fill": IMPROVEMENT_FILL, "stroke": IMPROVEMENT_STROKE},
    }
    return mapping.get(status, mapping["Needs Improvement"])[key]
 
 
def tile_positions(n: int, cols: int = 8):
    """Return (col_index, row_index) lists for n tiles in a left-to-right grid."""
    col_idx = [i % cols for i in range(n)]
    row_idx = [i // cols for i in range(n)]
    return col_idx, row_idx
 
 
# ── per-unit tile chart ──────────────────────────────────────────────────────
 
def unit_kc_chart(
    unit_name: str,
    unit_df: pd.DataFrame,
    mastery_threshold: float = 0.70,
    warning_threshold: float = 0.30,
    cols: int = 8,
    tile_size: int = 38,
    tile_gap: int = 6,
    label_width: int = 90,
) -> alt.Chart:
    """
    Build one row of the dashboard for a single unit.
 
    Parameters
    ----------
    unit_name         : display label shown on the left
    unit_df           : DataFrame with at least these columns:
                          - modeling_kc_label   (str)  KC name shown in tooltip
                          - state_predictions   (float) mastery probability 0–1
    mastery_threshold : score >= this  → Mastered
    warning_threshold : score <= this  → Needs Improvement
    cols              : max tiles per row inside the grid
    tile_size         : width/height of each square in px
    tile_gap          : gap between squares in px
    label_width       : pixel width reserved for the unit label on the left
    """
    df = unit_df.copy().reset_index(drop=True)
    df["status"] = df["pct_mastered"].apply(
        classify, args=(mastery_threshold, warning_threshold)
    )
 
    # grid positions (KC = one tile)
    col_idx, row_idx = tile_positions(len(df), cols)
    df["col"] = col_idx
    df["row"] = row_idx
 
    # colours
    df["fill"]   = df["status"].apply(lambda s: status_color(s, "fill"))
    df["stroke"] = df["status"].apply(lambda s: status_color(s, "stroke"))
 
    # grid dimensions
    step   = tile_size + tile_gap
    grid_w = cols * step - tile_gap
    n_rows = int(np.ceil(len(df) / cols))
    grid_h = n_rows * step - tile_gap
 
    # ── tile rectangles ──────────────────────────────────────────────────────
    tiles = (
        alt.Chart(df)
        .mark_rect(cornerRadius=5)
        .encode(
            x=alt.X(
                "col:O",
                scale=alt.Scale(
                    domain=list(range(cols)),
                    paddingInner=tile_gap / step,
                    paddingOuter=0,
                ),
                axis=None,
            ),
            y=alt.Y(
                "row:O",
                scale=alt.Scale(
                    domain=list(range(n_rows)),
                    paddingInner=tile_gap / step,
                    paddingOuter=0,
                ),
                axis=None,
            ),
            color=alt.Color("fill:N",   scale=None, legend=None),
            stroke=alt.Stroke("stroke:N", scale=None, legend=None),
            strokeWidth=alt.value(1.5),
            tooltip=[
                alt.Tooltip("modeling_kc_label:N", title="KC"),
                alt.Tooltip("pct_mastered:Q",  title="Mastery probability", format=".0%"),
                alt.Tooltip("status:N",              title="Status"),
            ],
        )
        .properties(width=grid_w, height=grid_h)
    )
 
    # ── unit label on the left ───────────────────────────────────────────────
    label_df = pd.DataFrame({"x": [0], "y": [0], "label": [unit_name]})
    label = (
        alt.Chart(label_df)
        .mark_text(
            align="right",
            baseline="middle",
            fontSize=14,
            fontWeight=500,
            color=TEXT_COLOR,
        )
        .encode(
            x=alt.X("x:Q", scale=alt.Scale(domain=[0, 1]), axis=None),
            y=alt.Y("y:Q", scale=alt.Scale(domain=[-1, 1]), axis=None),
            text="label:N",
        )
        .properties(width=label_width, height=grid_h)
    )
 
    return alt.hconcat(label, tiles, spacing=16).resolve_scale(
        x="independent", y="independent"
    )
 
 
# ── legend ───────────────────────────────────────────────────────────────────
 
def make_legend() -> alt.Chart:
    items = [
        {"status": "Mastered",          "fill": MASTERED_FILL,    "stroke": MASTERED_STROKE,    "x": 0},
        {"status": "Progressing",       "fill": PROGRESS_FILL,    "stroke": PROGRESS_STROKE,    "x": 1},
        {"status": "Needs Improvement", "fill": IMPROVEMENT_FILL, "stroke": IMPROVEMENT_STROKE, "x": 2},
    ]
    thresholds = ["≥ 70%", "30 – 70%", "≤ 30%"]
    for item, thr in zip(items, thresholds):
        item["label"] = f"{item['status']}  ({thr})"
 
    ldf = pd.DataFrame(items)
    ldf["y"] = 0
 
    squares = (
        alt.Chart(ldf)
        .mark_rect(cornerRadius=4, width=14, height=14)
        .encode(
            x=alt.X("x:O", axis=None),
            y=alt.Y("y:O", axis=None),
            color=alt.Color("fill:N",   scale=None, legend=None),
            stroke=alt.Stroke("stroke:N", scale=None, legend=None),
            strokeWidth=alt.value(1.5),
        )
    )
 
    labels = (
        alt.Chart(ldf)
        .mark_text(align="left", baseline="middle", dx=12, fontSize=12, color=LABEL_COLOR)
        .encode(
            x=alt.X("x:O", axis=None),
            y=alt.Y("y:O", axis=None),
            text="label:N",
        )
    )
 
    return (
        (squares + labels)
        .properties(width=520, height=24)
        .configure_view(strokeWidth=0)
    )

In [41]:
bar_data = mkc_data.copy()
last_attempt = bar_data.groupby(['user_id','skill_name']).last().reset_index()
last_attempt
mastery_threshold = 0.7

In [ ]:
def kc_mastery_dashboard(
    data: pd.DataFrame,
    unit_col: str = "unit",
    kc_col: str = "modeling_kc_label",
    score_col: str = "pct_mastered",
    mastery_threshold: float = 0.70,
    warning_threshold: float = 0.30,
    cols: int = 8,
    tile_size: int = 38,
    tile_gap: int = 6,
    label_width: int = 90,
    title: str = "KC Mastery Overview",
) -> alt.VConcatChart:
    """
    Build the full multi-unit KC mastery grid.
 
    Parameters
    ----------
    data              : DataFrame with columns for unit, KC label, and mastery score
    unit_col          : column name for the unit grouping  (default: "unit_name")
    kc_col            : column name for KC labels          (default: "modeling_kc_label")
    score_col         : column name for mastery scores     (default: "pct_mastered")
    mastery_threshold : score >= this  → Mastered          (default: 0.70)
    warning_threshold : score <= this  → Needs Improvement (default: 0.30)
    cols              : max tiles per row                   (default: 8)
    tile_size         : tile width/height in px             (default: 38)
    tile_gap          : gap between tiles in px             (default: 6)
    label_width       : width of the unit-name column       (default: 90)
    title             : chart title                         (default: "KC Mastery Overview")
    """

    pct_mastered = (
        data
        .groupby(['unit','skill_name','modeling_kc_label'])['state_predictions']
        .apply(lambda x: (x >= mastery_threshold).mean() * 100)
        .reset_index()
        .rename(columns={'state_predictions': 'pct_mastered'})
        .sort_values('pct_mastered', ascending=False)
    )

    df = pct_mastered.rename(columns={
        unit_col:  "unit_name",
        kc_col:    "modeling_kc_label",
        score_col: "pct_mastered",
    })

    return df
 
    # units = df["unit_name"].unique()
 
    # rows = [
    #     unit_kc_chart(
    #         unit_name=unit,
    #         unit_df=df[df["unit_name"] == unit][["modeling_kc_label", "pct_mastered"]],
    #         mastery_threshold=mastery_threshold,
    #         warning_threshold=warning_threshold,
    #         cols=cols,
    #         tile_size=tile_size,
    #         tile_gap=tile_gap,
    #         label_width=label_width,
    #     )
    #     for unit in units
    # ]
 
    # # summary counts
    # df["_status"] = df["pct_mastered"].apply(
    #     classify, args=(mastery_threshold, warning_threshold)
    # )
    # n_mastered    = (df["_status"] == "Mastered").sum()
    # n_progressing = (df["_status"] == "Progressing").sum()
    # n_needs       = (df["_status"] == "Needs Improvement").sum()
    # n_total       = len(df)
 
    # subtitle = (
    #     f"{n_mastered} mastered · "
    #     f"{n_progressing} progressing · "
    #     f"{n_needs} needs improvement · "
    #     f"{n_total} KCs total"
    # )
 
    # return (
    #     alt.vconcat(*rows, spacing=12)
    #     .properties(
    #         title=alt.Title(
    #             text=title,
    #             subtitle=subtitle,
    #             fontSize=16,
    #             subtitleFontSize=12,
    #             subtitleColor=LABEL_COLOR,
    #             anchor="start",
    #         )
    #     )
    #     .configure_view(strokeWidth=0)
    #     .configure_concat(spacing=12)
    # )

In [64]:
kc_mastery_dashboard(last_attempt)

,unit,skill_name,modeling_kc_label,pct_mastered
24,Unit 4,MKC.U4.05.geometric_model,Geometric model and binomial/geometric choice,100.000000
1,Unit 1,MKC.U1.02.categorical_tables_displays,"Categorical tables, displays, and association",100.000000
44,Unit 9,MKC.U9.01.slope_inference_foundations_ci,Regression slope inference foundations and con...,84.210526
28,Unit 5,MKC.U5.04.sample_mean_sampling_distribution,Sampling distribution of a sample mean,50.000000
45,Unit 9,MKC.U9.02.regression_conditions_diagnostics_scope,"Regression inference conditions, diagnostics, ...",43.750000
30,Unit 6,MKC.U6.01.one_prop_confidence_intervals,One-proportion confidence intervals,39.130435
12,Unit 2,MKC.U2.03.correlation_form_outliers_transform,"Correlation, form, outliers, and transformations",38.095238
20,Unit 4,MKC.U4.01.probability_foundations_simulation,Probability foundations and simulation,28.000000
26,Unit 5,MKC.U5.02.sample_proportion_sampling_distribution,Sampling distribution of a sample proportion,25.000000
6,Unit 10,MKC.U10.01.bootstrap_process_distribution,Bootstrap process and bootstrap distributions,25.000000
23,Unit 4,MKC.U4.04.binomial_model,Binomial model,24.000000
5,Unit 1,MKC.U1.06.normal_distribution_calculations,Normal distribution modeling and calculations,23.809524
25,Unit 5,MKC.U5.01.normal_simulation_estimators,"Normal models, simulation, and estimators",20.000000
43,Unit 8,MKC.U8.03.chi_square_two_way_calculation_concl...,"Two-way chi-square statistic, p-value, and con...",16.666667
33,Unit 6,MKC.U6.04.two_prop_confidence_intervals,Two-proportion confidence intervals,15.789474
3,Unit 1,MKC.U1.04.summary_statistics_outliers,"Summary statistics, percentiles, and outliers",13.043478
14,Unit 2,MKC.U2.05.residuals_r2_model_diagnostics,"Residuals, r-squared, and model diagnostics",9.090909
41,Unit 8,MKC.U8.01.chi_square_gof,Chi-square goodness-of-fit tests,8.695652
31,Unit 6,MKC.U6.02.one_prop_hypothesis_tests,One-proportion hypothesis tests,8.333333
15,Unit 3,MKC.U3.01.population_sampling_methods,Populations and sampling methods,8.333333
39,Unit 7,MKC.U7.05.two_sample_t_tests,Two-sample t-tests,4.761905
32,Unit 6,MKC.U6.03.errors_alpha_power,"Type I/II error, alpha, beta, and power",4.545455
42,Unit 8,MKC.U8.02.chi_square_two_way_structure,"Two-way chi-square structure, hypotheses, and ...",4.347826
40,Unit 7,MKC.U7.06.multiple_comparisons_family_error,Multiple comparisons and family error rate,0.000000
34,Unit 6,MKC.U6.05.two_prop_hypothesis_tests,Two-proportion hypothesis tests,0.000000
35,Unit 7,MKC.U7.01.t_intervals_mean_foundations,t-distribution and one-sample mean intervals,0.000000
36,Unit 7,MKC.U7.02.matched_pairs_mean_inference,Matched-pairs inference for means,0.000000
37,Unit 7,MKC.U7.03.one_sample_t_tests,One-sample and matched-pairs t-tests,0.000000
38,Unit 7,MKC.U7.04.two_sample_t_intervals,Two-sample t confidence intervals,0.000000
0,Unit 1,MKC.U1.01.data_context_variables,Data context and variable classification,0.000000
29,Unit 5,MKC.U5.05.diff_means_sampling_distribution,Sampling distribution of a difference in sampl...,0.000000
11,Unit 2,MKC.U2.02.scatterplots_and_association,Scatterplots and association description,0.000000
2,Unit 1,MKC.U1.03.quantitative_displays_description,Quantitative displays and distribution descrip...,0.000000
4,Unit 1,MKC.U1.05.standardization_transformations,Standardization and linear transformations,0.000000
7,Unit 10,MKC.U10.02.bootstrap_intervals,Bootstrap percentile intervals,0.000000
8,Unit 10,MKC.U10.03.effect_size_practical_importance,Effect size and practical importance,0.000000
9,Unit 10,MKC.U10.04.power_typeii_tradeoffs,"Power, Type II error, and alpha-beta tradeoffs",0.000000
10,Unit 2,MKC.U2.01.two_way_categorical_association,Two-way categorical association,0.000000
13,Unit 2,MKC.U2.04.regression_prediction_interpretation,Regression prediction and coefficient interpre...,0.000000
27,Unit 5,MKC.U5.03.diff_proportions_sampling_distribution,Sampling distribution of a difference in sampl...,0.000000
16,Unit 3,MKC.U3.02.bias_and_generalization,Bias and scope of generalization,0.000000
17,Unit 3,MKC.U3.03.study_type_variables_units,"Study type, variables, treatments, and experim...",0.000000
18,Unit 3,MKC.U3.04.random_assignment_causation_design,"Random assignment, replication, and causal con...",0.000000
19,Unit 3,MKC.U3.05.blocking_matching_blinding_confounding,"Blocking, matched pairs, blinding, and confoun...",0.000000
21,Unit 4,MKC.U4.02.conditional_compound_independence,"Conditional, compound, and independent-event p...",0.000000
22,Unit 4,MKC.U4.03.random_variables_expected_value,"Random variables, probability distributions, a...",0.000000
46,Unit 9,MKC.U9.03.slope_hypothesis_tests,Regression slope hypothesis tests,0.000000

In [23]:
last_attempt[last_attempt['unit']=='Unit 1'].groupby('modeling_kc_label').agg('count')

,user_id,skill_name,correct,order_id,correct_predictions,state_predictions,unit,topic_group,description,num_fine_kcs,...,weight,tier,estimated_exam_share_pct,unit_exam_weighting,direct_dependents,downstream_dependents,weighted_direct_edge_count,weight_rationale,2026_27_revision_note,kc_attempt
modeling_kc_label,,,,,,,,,,,,,,,,,,,,,
"Categorical tables, displays, and association",22,22,22,22,22,22,22,22,22,22,...,22,22,22,22,22,22,22,22,0,22
Data context and variable classification,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,0,13
Normal distribution modeling and calculations,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,21,0,21
Quantitative displays and distribution description,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,0,19
Standardization and linear transformations,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,0,19
"Summary statistics, percentiles, and outliers",23,23,23,23,23,23,23,23,23,23,...,23,23,23,23,23,23,23,23,0,23

In [24]:
unit_mastery_box('Unit 1',last_attempt[last_attempt['unit']=='Unit 1'])

NameError: name 'unit_mastery_box' is not defined